config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  root 'welcome#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact< MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
        :subject => "Contact Form",
        :to => "triko2020@gmail.com",
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId

  has_attached_file :image,
 styles: { large: "700x700>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  friendly_id :title, use: :slugged
  

end

app/models/project.rb
class Project < ApplicationRecord
    
    extend FriendlyId
    has_attached_file :picture, styles: { large: "700x700>", medium: "300x300>", thumb: "150x150#" }
    validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
    friendly_id :title, use: :slugged
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:  [:index, :show]
  def index
  @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 5)
  end

  def new
    @post = Post.new
  end
  
  def create 
    @post = Post.new post_params
    if @post.save
      redirect_to @post, notice: "Article Saved"
    else
      render 'new', notice: "Article not save"
    end
  end
  def show

  end
  def edit

  end
  def update
if @post.update post_params
  redirect_to @post, notice: "Article update"
else
  render 'edit'
end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end
  private
  def post_params 
    params.require(:post).permit(:title, :content, :slug, :image);
  end
  def find_post
    @post = Post.friendly.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project , only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @projects = Project.all.order("created_at desc")
  end
  def show
  end

  def new
    @project = Project.new
  end

  def create 
  @project = Project.new project_params
  if @project.save
    redirect_to @project, notice: "Article Saved"
  else
    render 'new', notice: "Article not save"
  end
end

  def edit
  end

  def update
 if @project.update project_params
   redirect_to @project, notice: "Project update"
 else
   render 'edit'
 end
  end
  def destroy
@project.destroy
    redirect_to projects_path
  end

  private
  def find_project
    @project = Project.friendly.find(params[:id])
  end
  def project_params
    params.required(:project).permit(:title, :description, :link, :picture)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.limit(6).order("created_at desc")
    @projects = Project.all.limit(6).order("created_at desc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
  options = {
      autolink: true,
      no_intra_empasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
  }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="artical_title">Hello</h1>
<div class="skinny_wrapper wrapper_padding">

  <h1>Thank you for your message!New brach</h1>
  <p>I'll get back yo you soon.Brach Masterі</p>
</div>

app/views/contacts/new.html.erb
<h1 id="artical_title">Send Message</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= form_for @contact do |f| %>
      <%= f.label :name %> <br>
      <%= f.text_field :name, require: true %>

      <br>
      <%= f.label :email %> <br>
      <%= f.text_field :email, require: true %>

      <br>
      <%= f.label :message %> <br>
      <%= f.text_area :message, require: true %>

      <br>

<div class="hidden">
  <%= f.label :nickname %> <br>
  <%= f.text_field :nickname, hint: 'leave this field blank' %>
</div>

      <%=  f.submit 'Send Message', class: "button" %>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Andriy Shevchuk </title>
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header id="main_navigation" class="clearfix" >
    <%= link_to "Andriy_Shevchuk", root_path, class: "name" %>

    <nav>
      <%= link_to "Articles", posts_path %>
      <%= link_to "Projects", projects_path %>
      <%= link_to "Contacts", new_contact_path %>
      <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          <% end %>

    </nav>
  </header>
  <% if notice %>
  <p class="notice"><%= notice %></p>
      <% elsif alert %>
  <p class="alert"><%= alert %></p>
<% end %>
  <%= yield %>
  <footer id="footer">
    <p class="copyright">&copy; 2016 Andriy Shevchyk</p>
    <nav>
      <a href="#"><i class="fa fa-vk" aria-hidden="true"></i></a>
      <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
      <a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
    </nav>
  </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
    <% if @post.errors.any? %>
        <h2><%= pluralize(@post.errors.count, "error") %> prevented this post form saving:</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
    <br>
    <br>

    <%= f.label :content, "Write your article here!" %> <br>
    <%= f.text_area :content%>
    <br>
    <br>
    <%= f.label :image %> <br>
    <%= f.file_field :image %>
    <br>
    <br>

    <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div class="skinny_wrapper wrapper_padding">
<h1>Edit Post</h1>
<%= render 'form'%>
</div>

app/views/posts/index.html.erb
<h1 id="artical_title">Stuff i Design
  <% if user_signed_in? %>

      <%= link_to "add Article", new_post_path(@post), class: "add_links" %>
  
  <% end %>
  </h1>



<div id="posts_wrapper" class="skinny_wrapper">
  <% @posts.each do |post| %>
      <div class="post">
        <p class="date"><%= post.created_at.strftime('%A, %b %d') %></p>
        <h2><a href="#"><%= link_to post.title, post %></a></h2>
        <hr>
      </div>
      <% end %>


</div>
<%= will_paginate @posts %>

app/views/posts/new.html.erb
<div class="skinny_wrapper wrapper_padding">
<h1>New</h1>
<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
<header>
  <p class="date"><%= @post.created_at.strftime("%A, %b %d") %></p>
  <h1><%=@post.title %></h1>
  <%= image_tag @post.image.url(:large)%>
  <hr>  
</header>
<div id="content">
  <%= markdown @post.content %>
</div>
<% if user_signed_in? %>
  <div id="admin_links">
    <%= link_to "Edit Article", edit_post_path(@post) %>
    <%= link_to "Delete Article", post_path(@post), method: :delete, data: {confirm: "Are u sure?"} %>
  </div>
      <% end %>
  <hr>
<div id="share_box">
  <p>Share The DO List</p>
  <a href=""><i class="fa fa-twitter"></i></a>
  <i class="fa fa-vk"></i></a>
  <i class="fa fa-google-plus"></i></a>
</div>
  <hr>
  <div id="disqus_thread"></div>
  <script>

      var disqus_shortname = 'portfolio';

      (function() { // DON'T EDIT BELOW THIS LINE
          var d = document, s = d.createElement('script');
          s.src = '//blogg-1.disqus.com/embed.js';
          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
      })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

</div>

app/views/projects/_form.html.erb
<%= form_for @project, html: { multipart: true } do |f| %>
    <% if @project .errors.any? %>
        <h2><%= pluralize(@project.errors.count, "erorr") %> prevented this post form saving:</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
    <br>
    <br>

    <%= f.label :description, "Write your description here" %> <br>
    <%= f.text_area :description%>
    <br>
    <br>
    <%= f.label :link %> <br>
    <%= f.text_field :link %>
    <br>
    <br>
    <%= f.label :picture %> <br>
    <%= f.file_field :picture, :multiple =>:true %>

    <br>
    <br>
    <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<div class="skinny_wrapper wrapper_padding">
  <h1>Edit Project</h1>
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="artical_title">Stuff i Design
  <% if user_signed_in? %>

      <%= link_to "Add Project", new_project_path(@post), class: "add_links" %>

  <% end %>
</h1>

<div id="posts_wrapper" class="skinny_wrapper">
  <% @projects.each do |project| %>
      <div class="post">
        <p class="date"><%= project.created_at.strftime('%A, %b %d') %></p>
        <h2><a href="#"><%= link_to project.title, project %></a></h2>
        <hr>
      </div>
  <% end %>


</div>

app/views/projects/new.html.erb
<div class="skinny_wrapper wrapper_padding">
  <h1>New Project</h1>
<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @project.created_at.strftime("%A, %b %d") %></p>
    <h1><%=@project.title %></h1>
    <%= image_tag @project.picture.url(:large) %>
    <hr>
  </header>
  <div id="content">
    <%= markdown @project.description%>
    <div class="button_wrapper">
    <a href="<%= @project.link %>" class="project_button" target="_blank">Visit <%= @project.title %></a>
  </div>
  </div>
  <% if user_signed_in? %>
      <div id="admin_links">
        <%= link_to "Edit Project", edit_project_path(@project) %>
        <%= link_to "Delete Project", project_path(@project), method: :delete, data: {confirm: "Are u sure?"} %>
      </div>
  <% end %>
  <hr>
  <div id="disqus_thread"></div>
  <script>

      var disqus_shortname = 'portfolio';

      (function() { // DON'T EDIT BELOW THIS LINE
          var d = document, s = d.createElement('script');
          s.src = '//blogg-1.disqus.com/embed.js';
          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
      })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
  <div class="col homepage">
    <h2>Portfolio</h2>
    <hr>
    <% @projects.each do |project| %>
    <div class="col-img">
        <%= link_to project do %>
        <%= image_tag project.picture.url(:large) %>
        <% end %>
      </div> 
    <% end %>
    
  </div>
  </div>
<div class="wrapper wrapper_padding clearfix">
  <div class="col homepage">
    <h2>About Me</h2>
    <hr>
    <p>Hello!</p>
    <p>I'm Andriy, 21 years old.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
  </div>


</div>

</div>